# Generated by Django 6.0.1 on 2026-01-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
