# Generated by Django 6.0.1 on 2026-01-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False), ('start_time__isnull', False)), fields=('trip_day', 'place', 'start_time'), name='unique_event_per_trip_day'),
        ),
    ]
