# Generated by Django 6.0.1 on 2026-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_usertrip_unique_user_trip_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
