# Generated by Django 6.0.1 on 2026-01-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_alter_event_duration_event_unique_event_per_trip_day'),
        ('itineraries', '0003_alter_lodging_location_text'),
    ]

    operations = [
    ]
