# Generated by Django 6.0.1 on 2026-02-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_remove_event_location_text_remove_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripday',
            name='name',
        ),
    ]
