# Generated by Django 6.0.1 on 2026-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_remove_tripday_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lodging',
            name='unique_lodging_per_trip',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='name',
        ),
    ]
